stages:
  - build

variables:
  # Prevent interactive prompts in LaTeX
  TEXINPUTS: ".:"

build_latex:
  image: texlive/texlive:latest
  stage: build
  script:
    # Setup
    - apt-get update && apt-get install -y python3-venv biber qpdf
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install Pygments
    # Build
    - python3 latex.py --verbose --log-file latex.log build --silent
    # Information
    - python3 latex.py --version >> build/info.log 2>&1
    - python3 latex.py --verbose info >> build/info.log 2>&1
  artifacts:
    paths:
      # PDFs
      - build/*.pdf
      # Logs
      - latex.log
      - build/*.log
      - build/**/*.log
    exclude:
      - build/*_uncompressed.pdf
      - build/*_unoptimized.pdf
    expire_in: 1 week
  only:
    - main
    - merge_requests
